### ISSUE TITLE
When editing a document type, vorto can't find contentTypeAlias

### ISSUE THREAD

**Issue by rasmuseeg** [umco/umbraco-vorto#69]
angular.min.js?cdv=1555615759:106 GET http://localhost:24292/umbraco/backoffice/VortoApi/VortoApi/GetLanguages?section=settings&id=149349&parentId=148761&dtdGuid=undefined 400 (Bad Request)

**Comment by mattbrailsford** [comment]
Fixed in e4189544b04ddb6c63e2ae9ab8e2dfab2d7d6e1d

**Comment by jajeffries** [comment]
We are still seeing this issue with version 7.5.6 of umbraco and 1.5.3 of vorto.

The contentTypeAlias parameter of the GetDataTypeByAlias is undefined.
